### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by VampiricAlien** [ShiniGandhi/Backdroppr#2]
It's hard to understand if it's working or not without some kind of log file or more information in the command line.

**Comment by Amarel-LTD** [comment]
Hmm, it should print out logs. are you sure your configuration is correct? what does it show when you run it?

**Comment by VampiricAlien** [comment]
`2023-01-08 08:21:27,577 Movie trailer finder started.`
Nothing else happens, after that I edited the config (forgot before ran command) but still same out put.

Shouldn't more show?

**Comment by Amarel-LTD** [comment]
It should. Can you show me your config?

**Comment by VampiricAlien** [comment]
```
### Mandatory ###
radarr_api: "my API key here"
radarr_host: "link here:7878"
sonarr_api: "my api key here"
sonarr_host: "link here:8989"
tmdb_api: "api key here"
output_dirs: "trailers"
### Optional ###
filetype: "webm"
sleep_time: 3
length_range: "30,300"
skip_intros: True
thread_count: 8
subs: True
### Uncomment if needed ###
moviepath: "link to movies"
tvpath: "link to tv"

```
I've removed links and keys from the config I posted.

**Comment by Amarel-LTD** [comment]
Make sure the IP and API keys are correct, I'll try to work on a fix for this regardless when I get off work.

**Comment by VampiricAlien** [comment]
Turns out if IP is wrong nothing is said, are you able to add  a pre check?

I think this happens on slow connections? WARNING: [youtube:search] <urlopen error _ssl.c:980: The handshake operation timed out>. Retrying ...

**Comment by Amarel-LTD** [comment]
Yeah I'll add a pre-check in the next version.
About the youtube thing, can you reiterate? Also, the `skip_intros` flag sometimes causes connection issues to youtube because of an issue with yt-dlp. Try to disable it for a while.

**Comment by VampiricAlien** [comment]
Thanks, I'll give that a try when I am able too.
